DROP DATABASE IF EXISTS js_db;

CREATE DATABASE js_db DEFAULT CHARSET utf8mb4;

USE js_db;

CREATE TABLE users(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE messages(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    content LONGTEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT UNSIGNED,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;